Repository HorlogeSkynet/archey4, pull requests merged in 2020-10, with the labels that each got.

#83 [DISTROS] Add support for Elementary OS
  archey/constants.py
  archey/distributions.py
  archey/logos/__init__.py
  archey/logos/elementary.py
Labels: enhancement :arrow_up:, hacktoberfest

#80 [FEATURE] [BREAKING] Change configuration layout
  README.md
  archey/__main__.py
  archey/config.json
  archey/constants.py
  archey/entries/disk.py
  archey/entries/distro.py
  archey/entries/gpu.py
  archey/entries/lan_ip.py
  archey/entries/model.py
  archey/entries/ram.py
  archey/entries/temperature.py
  archey/entries/terminal.py
  archey/entries/wan_ip.py
  archey/entry.py
  archey/output.py
  archey/test/entries/__init__.py
  archey/test/entries/test_archey_disk.py
  archey/test/entries/test_archey_gpu.py
  archey/test/entries/test_archey_lan_ip.py
  archey/test/entries/test_archey_model.py
  archey/test/entries/test_archey_ram.py
  archey/test/entries/test_archey_temperature.py
  archey/test/entries/test_archey_terminal.py
  archey/test/entries/test_archey_wan_ip.py
  archey/test/test_archey_entry.py
  archey/test/test_archey_output.py
Labels: backward compatibility :arrow_down:, enhancement :arrow_up:, typo :pencil2:

#86 [SCREENSHOT] Fixes usages of unknown `.rpart` method
  archey/screenshot.py
Labels: bug :bug:, hacktoberfest-accepted

#87 [FEATURE] Exits with non-zero status code on Unicode or screenshot error
  archey/output.py
  archey/screenshot.py
Labels: enhancement :arrow_up:, hacktoberfest-accepted

#84 [DISTROS] Add support for Pop!_OS
  archey/constants.py
  archey/distributions.py
  archey/logos/__init__.py
  archey/logos/pop.py
Labels: enhancement :arrow_up:, hacktoberfest-accepted

#88 [MODEL] Adds hardware product version if available
  archey/entries/model.py
  archey/test/entries/test_archey_model.py
Labels: enhancement :arrow_up:, hacktoberfest-accepted

#90 [CPU] [FEATURE/BREAKING] Multiple CPUs support
  README.md
  archey/entries/cpu.py
  archey/entries/gpu.py
  archey/test/entries/test_archey_cpu.py
  archey/test/entries/test_archey_gpu.py
  config.json
Labels: enhancement :arrow_up:
