Repository HorlogeSkynet/archey4, pull requests merged in 2020-05, with the labels that each got.

#64 Reworks the `Output` class
  .pylintrc
  archey/__main__.py
  archey/colors.py
  archey/entries/cpu.py
  archey/entries/desktop_environment.py
  archey/entries/disk.py
  archey/entries/distro.py
  archey/entries/gpu.py
  archey/entries/hostname.py
  archey/entries/kernel.py
  archey/entries/lan_ip.py
  archey/entries/model.py
  archey/entries/packages.py
  archey/entries/ram.py
  archey/entries/shell.py
  archey/entries/temperature.py
  archey/entries/terminal.py
  archey/entries/uptime.py
  archey/entries/user.py
  archey/entries/wan_ip.py
  archey/entries/window_manager.py
  archey/entry.py
  archey/logos/__init__.py
  archey/logos/alpine_linux.py
  archey/logos/arch_linux.py
  archey/logos/bunsenlabs.py
  archey/logos/centos.py
  archey/logos/crunchbang.py
  archey/logos/debian.py
  archey/logos/fedora.py
  archey/logos/gentoo.py
  archey/logos/kali_linux.py
  archey/logos/linux.py
  archey/logos/linux_mint.py
  archey/logos/manjaro.py
  archey/logos/opensuse.py
  archey/logos/red_hat.py
  archey/logos/slackware.py
  archey/logos/ubuntu.py
  archey/logos/windows.py
  archey/output.py
  archey/test/test_archey_colors.py
  archey/test/test_archey_disk.py
  archey/test/test_archey_distro.py
  archey/test/test_archey_entry.py
  archey/test/test_archey_gpu.py
  archey/test/test_archey_lan_ip.py
  archey/test/test_archey_logos.py
  archey/test/test_archey_model.py
  archey/test/test_archey_output.py
  archey/test/test_archey_packages.py
  archey/test/test_archey_ram.py
  archey/test/test_archey_shell.py
  archey/test/test_archey_temperature.py
  archey/test/test_archey_terminal.py
  archey/test/test_archey_user.py
  archey/test/test_archey_version.py
  archey/test/test_archey_wan_ip.py
  archey/test/test_archey_window_manager.py
Labels: bug :bug:, enhancement :arrow_up:

#66 [BUGFIX] Fix crash if no read permissions for /proc/uptime, and use fallbacks instead
  archey/entries/uptime.py
  archey/processes.py
  archey/test/test_archey_uptime.py
Labels: bug :bug:, enhancement :arrow_up:

#71 [GPU] Adds support for multiple GPUs (and fixes their display order)
  README.md
  archey/config.json
  archey/configuration.py
  archey/entries/gpu.py
  archey/entry.py
  archey/output.py
  archey/test/test_archey_gpu.py
  archey/test/test_archey_output.py
Labels: bug :bug:, enhancement :arrow_up:

#73 [CONFIG] Modify `config.json` with proper defaults
  archey/config.json
Labels: backward compatibility :arrow_down:

#72 [TERMINAL] Improves terminal detection based on environment variables
  archey/entries/terminal.py
  archey/test/test_archey_terminal.py
Labels: enhancement :arrow_up:

#70 [FEATURE] JSON output format
  archey/__main__.py
  archey/api.py
  archey/colors.py
  archey/entries/desktop_environment.py
  archey/entries/disk.py
  archey/entries/distro.py
  archey/entries/gpu.py
  archey/entries/lan_ip.py
  archey/entries/model.py
  archey/entries/packages.py
  archey/entries/ram.py
  archey/entries/shell.py
  archey/entries/temperature.py
  archey/entries/terminal.py
  archey/entries/uptime.py
  archey/entries/user.py
  archey/entries/wan_ip.py
  archey/entries/window_manager.py
  archey/entry.py
  archey/output.py
  archey/test/__init__.py
  archey/test/test_archey_api.py
  archey/test/test_archey_colors.py
  archey/test/test_archey_desktop_environment.py
  archey/test/test_archey_disk.py
  archey/test/test_archey_distro.py
  archey/test/test_archey_gpu.py
  archey/test/test_archey_lan_ip.py
  archey/test/test_archey_model.py
  archey/test/test_archey_output.py
  archey/test/test_archey_packages.py
  archey/test/test_archey_ram.py
  archey/test/test_archey_shell.py
  archey/test/test_archey_temperature.py
  archey/test/test_archey_terminal.py
  archey/test/test_archey_uptime.py
  archey/test/test_archey_user.py
  archey/test/test_archey_wan_ip.py
  archey/test/test_archey_window_manager.py
Labels: enhancement :arrow_up:

#74 [FEATURE] Makes entries being loaded in parallel
  README.md
  archey/__main__.py
  archey/config.json
  archey/configuration.py
Labels: enhancement :arrow_up:

#67 [WIP] Disk entry rework
  README.md
  archey/config.json
  archey/configuration.py
  archey/entries/disk.py
  archey/test/test_archey_disk.py
  packaging/build.sh
Labels: bug :bug:, enhancement :arrow_up:, question :grey_question:
